version: "3.2"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
  app:
    build: .
    ports:
      - '8050:8050'
    environment: 
      MONGO_DB_HOST: mongodb
      TELEGRAM_CHAT_ID: -595188264
    depends_on:
      - mongodb
volumes: 
  data:
  logs:
